name: Build and Release RPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build RPM in Fedora container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace fedora:latest \
        bash -c "
          dnf install -y rpm-build mock tar gzip && \
          mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
          mkdir -p /workspace/rpmbuild && \
          mkdir /workspace/mypackage-1.0 && \
          cp -r /workspace/src /workspace/mypackage-1.0/ && \
          tar czf /root/rpmbuild/SOURCES/mypackage-1.0.tar.gz -C /workspace mypackage-1.0 && \
          rpmbuild -ba /workspace/mypackage.spec && \
          echo 'Copying RPMs to workspace...' && \
          cp -r /root/rpmbuild/RPMS/noarch /workspace/rpmbuild/ && \
          echo 'Listing /workspace/rpmbuild/noarch/:' && \
          ls -R /workspace/rpmbuild/noarch/
        "

    - name: Upload built RPMs
      uses: actions/upload-artifact@v3
      with:
        name: RPMs
        path: /workspace/rpmbuild/noarch/**/*.rpm

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # Adjust version as needed
        release_name: "Release v1.0.0"
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /workspace/rpmbuild/noarch/mypackage-1.0-1.fc40.noarch.rpm
        asset_name: mypackage-1.0-1.noarch.rpm
        asset_content_type: application/octet-stream

