name: Build RPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: sudo apt install -y rpm rpm-build mock

    - name: Prepare the source tarball
      run: tar czf SOURCES/mypackage-1.0.tar.gz src/

    - name: Build the RPM
      run: |
        rpmbuild -ba mypackage.spec

    - name: Upload built RPMs
      uses: actions/upload-artifact@v2
      with:
        name: RPMs
        path: ~/rpmbuild/RPMS/

