name: Build RPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build RPM in Fedora container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace fedora:latest \
        bash -c "
          dnf install -y rpm-build mock tar gzip && \
          mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
          cd /root/rpmbuild/SOURCES && \
          tar czf mypackage-1.0.tar.gz /workspace/src && \
          cd /workspace && \
          rpmbuild -ba mypackage.spec
        "

    - name: Upload built RPMs
      uses: actions/upload-artifact@v3
      with:
        name: RPMs
        path: /workspace/rpmbuild/RPMS/

