name: Build RPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Still uses Ubuntu runner, but we'll use a CentOS/Fedora container

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build RPM inside CentOS container
      uses: docker://fedora:latest  # You can also use "centos:7" or "centos:8" depending on your preference
      run: |
        dnf install -y rpm-build mock tar gzip
        mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
        cd /root/rpmbuild/SOURCES
        tar czf mypackage-1.0.tar.gz /github/workspace/src/
        cd /github/workspace
        rpmbuild -ba mypackage.spec

    - name: Upload built RPMs
      uses: actions/upload-artifact@v3
      with:
        name: RPMs
        path: /root/rpmbuild/RPMS/

