name: Build and Upload RPM

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This grants the necessary permissions for uploading artifacts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build RPM in Fedora container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace fedora:latest \
        bash -c "
          dnf install -y rpm-build mock tar gzip && \
          mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
          mkdir -p /workspace/rpmbuild/noarch && \
          mkdir /workspace/mypackage-1.0 && \
          cp -r /workspace/src /workspace/mypackage-1.0/ && \
          tar czf /root/rpmbuild/SOURCES/mypackage-1.0.tar.gz -C /workspace mypackage-1.0 && \
          rpmbuild -ba /workspace/mypackage.spec && \
          echo 'Copying RPM to workspace...' && \
          cp /root/rpmbuild/RPMS/noarch/*.rpm /workspace/rpmbuild/noarch/ && \
          echo 'Listing /workspace/rpmbuild/noarch/:' && \
          ls -R /workspace/rpmbuild/noarch/
        "

    - name: Upload built RPMs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RPMs
        path: /workspace/rpmbuild/noarch/**/*.rpm

